title: Data Interview Essential
description: Interview tips for DS/MLE/DE/DA
theme: just-the-docs

url: https://data-interview-essential.github.io/interview

aux_links:
  Template Repository: https://github.com/data-interview-essential/interview
